---
name: Acme-CPANAuthors-Turkish
version: 0.11
author:
  - 'Burak Gursoy <burak@cpan.org>'
abstract: Türk CPAN Yazarları
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://bitbucket.org/burak/cpan-acme-cpanauthors-turkish/
requires:
  Acme::CPANAuthors: 0
build_requires:
  Test::More: 0.40
provides:
  Acme::CPANAuthors::Turkish:
    file: lib/Acme/CPANAuthors/Turkish.pm
    version: 0.11
no_index:
  directory:
    - tools
    - t
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
